// Generated by CoffeeScript 1.8.0
(function() {
  var Cam, assert, serverMockup;

  assert = require('assert');

  Cam = require('../lib/onvif').Cam;

  serverMockup = require('./serverMockup');

  describe('Simple and common get functions', function() {
    var cam;
    cam = null;
    before(function(done) {
      var options;
      options = {
        hostname: process.env.HOSTNAME || 'localhost',
        username: 'admin',
        password: '9999',
        port: process.env.PORT ? parseInt(process.env.PORT) : 10101
      };
      return cam = new Cam(options, done);
    });
    describe('getCapabilities', function() {
      it('should return an capabilities object with correspondent properties and also set them into capability property', function(done) {
        return cam.getCapabilities(function(err, data) {
          assert.equal(err, null);
          assert.ok(cam.profiles.every(function(profile) {
            return ['name', 'videoSourceConfiguration', 'videoEncoderConfiguration', 'PTZConfiguration'].every(function(prop) {
              return profile[prop];
            });
          }));
          assert.equal(cam.capabilities, data);
          return done();
        });
      });
      return it('should store PTZ link in ptzUri property', function(done) {
        assert.equal(cam.ptzUri.href, cam.capabilities.PTZ.XAddr);
        return done();
      });
    });
    describe('getVideoSources', function() {
      return it('should return a videosources object with correspondent properties and also set them into videoSources property', function(done) {
        return cam.getVideoSources(function(err, data) {
          assert.equal(err, null);
          assert.ok(['$', 'framerate', 'resolution'].every(function(prop) {
            return data[prop] !== void 0;
          }));
          assert.equal(cam.videoSources, data);
          return done();
        });
      });
    });
    describe('getProfiles', function() {
      return it('should create an array of profile objects with correspondent properties', function(done) {
        return cam.getVideoSources(function(err, data) {
          assert.equal(err, null);
          assert.ok(['$', 'framerate', 'resolution'].every(function(prop) {
            return data[prop] !== void 0;
          }));
          assert.equal(cam.videoSources, data);
          return done();
        });
      });
    });
    describe('getSystemDateAndTime', function() {
      return it('should return valid date', function(done) {
        return cam.getSystemDateAndTime(function(err, data) {
          assert.equal(err, null);
          assert.ok(data instanceof Date);
          return done();
        });
      });
    });
    describe('getServices', function() {
      return it('should return an array of services objects', function(done) {
        return cam.getServices(function(err, data) {
          assert.equal(err, null);
          assert.ok(Array.isArray(data));
          assert.ok(data.every(function(service) {
            return service.namespace && service.XAddr && service.version;
          }));
          return done();
        });
      });
    });
    describe('getDeviceInformation', function() {
      return it('should return an information about device', function(done) {
        return cam.getDeviceInformation(function(err, data) {
          assert.equal(err, null);
          assert.ok(['manufacturer', 'model', 'firmwareVersion', 'serialNumber', 'hardwareId'].every(function(prop) {
            return data[prop] !== void 0;
          }));
          assert.equal(cam.deviceInformation, data);
          return done();
        });
      });
    });
    describe('getStreamUri', function() {
      return it('should return a media stream uri', function(done) {
        return cam.getStreamUri({
          protocol: 'HTTP'
        }, function(err, data) {
          assert.equal(err, null);
          assert.ok(['uri', 'invalidAfterConnect', 'invalidAfterReboot', 'timeout'].every(function(prop) {
            return data[prop] !== void 0;
          }));
          return done();
        });
      });
    });
    return describe('getPresets', function() {
      return it('should return array of preset objects', function(done) {
        return cam.getPresets({}, function(err, data) {
          assert.equal(err, null);
          assert.ok(Object.keys(data).every(function(presetName) {
            return typeof data[presetName] === 'string';
          }));
          assert.equal(cam.presets, data);
          return done();
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=common.js.map
