// Generated by CoffeeScript 1.9.2
(function() {
  var assert, onvif, serverMockup;

  assert = require('assert');

  onvif = require('../lib/onvif');

  serverMockup = require('./serverMockup');

  describe('Events', function() {
    var cam;
    cam = null;
    before(function(done) {
      var options;
      options = {
        hostname: process.env.HOSTNAME || 'localhost',
        username: 'admin',
        password: '9999',
        port: process.env.PORT ? parseInt(process.env.PORT) : 10101
      };
      return cam = new onvif.Cam(options, done);
    });
    it('should request device events', function(done) {
      return cam.getEventProperties(function(err, res) {
        assert.equal(err, null);
        assert.deepEqual(this.events.properties, res);
        return done();
      });
    });
    it('should request event service capabilities', function(done) {
      return cam.getEventServiceCapabilities(function(err, res) {
        assert.equal(err, null);
        assert.ok(['PersistentNotificationStorage', 'MaxPullPoints', 'MaxNotificationProducers', 'WSPausableSubscriptionManagerInterfaceSupport', 'WSPullPointSupport', 'WSSubscriptionPolicySupport'].every(function(name) {
          return res[name] !== void 0;
        }));
        return done();
      });
    });
    it('should throws an error in PullMessages method when no pull-point subscription exists', function(done) {
      assert.throws(function() {
        return cam.pullMessages({}, function() {
          return {};
        });
      });
      return done();
    });
    it('should create PullPointSubscription', function(done) {
      return cam.createPullPointSubscription(function(err, data) {
        assert.equal(err, null);
        assert.deepEqual(data, cam.events.subscription);
        return done();
      });
    });
    it('should get messages with PullMessage method', function(done) {
      return cam.pullMessages({}, function(err, data) {
        assert.equal(err, null);
        assert.ok(['currentTime', 'terminationTime'].every(function(name) {
          return data[name] !== void 0;
        }));
        return done();
      });
    });
    it('should create PullPoint subscription via `event` event and receive events from mockup server', function(done) {
      var gotMessage, onEvent;
      delete cam.events.terminationTime;
      gotMessage = 0;
      onEvent = function(msg) {
        return gotMessage += 1;
      };
      cam.on('event', onEvent);
      return setTimeout(function() {
        assert.ok(cam.events.terminationTime !== void 0);
        assert.ok(gotMessage > 0);
        cam.removeListener('event', onEvent);
        return done();
      }, 30);
    });
    return it('should stop pulling when nobody is listen to `event` event', function(done) {
      delete cam.events.terminationTime;
      return setTimeout(function() {
        assert.ok(cam.events.terminationTime === void 0);
        return done();
      }, 30);
    });
  });

}).call(this);

//# sourceMappingURL=events.js.map
