// Generated by CoffeeScript 1.7.1
(function() {
  var assert, onvif, serverMockup, util;

  assert = require('assert');

  onvif = require('../lib/onvif');

  serverMockup = require('./serverMockup');

  util = require('util');

  describe('PTZ', function() {
    var cam;
    cam = null;
    before(function(done) {
      var options;
      options = {
        hostname: process.env.HOSTNAME || 'localhost',
        username: process.env.USERNAME || 'admin',
        password: process.env.PASSWORD || '9999',
        port: process.env.PORT ? parseInt(process.env.PORT) : 10101
      };
      return cam = new onvif.Cam(options, done);
    });
    return describe('getPresets', function() {
      return it('should return array of preset objects and sets them to #presets', function(done) {
        return cam.getPresets({}, function(err, data) {
          assert.equal(err, null);
          assert.ok(Object.keys(data).every(function(presetName) {
            return typeof data[presetName] === 'string';
          }));
          assert.equal(cam.presets, data);
          return done();
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=ptz.map
