// Generated by CoffeeScript 1.9.2
(function() {
  var Buffer, dgram, discover, fs, http, listener, reBody, reCommand, reNS;

  http = require('http');

  dgram = require('dgram');

  fs = require('fs');

  Buffer = (require('buffer')).Buffer;

  reBody = /<s:Body xmlns:xsi="http:\/\/www.w3.org\/2001\/XMLSchema-instance" xmlns:xsd="http:\/\/www.w3.org\/2001\/XMLSchema">(.*)<\/s:Body>/;

  reCommand = /<(\S*) /;

  reNS = /xmlns="http:\/\/www.onvif.org\/\S*\/(\S*)\/wsdl"/;

  listener = function(req, res) {
    var buf;
    req.setEncoding('utf8');
    buf = [];
    req.on('data', function(chunk) {
      return buf.push(chunk);
    });
    return req.on('end', function() {
      var body, command, ns, request;
      request = Buffer.concat(buf);
      body = reBody.exec(request);
      if (!body) {
        return res.end();
      }
      body = body[1];
      command = reCommand.exec(body)[1];
      ns = reNS.exec(body)[1];
      if (!command) {
        return res.end();
      }
      switch (false) {
        case !fs.existsSync(__dirname + '/serverMockup/' + ns + '.' + command + '.xml'):
          command = ns + '.' + command;
          break;
        case !!fs.existsSync(__dirname + '/serverMockup/' + command + '.xml'):
          command = 'Error';
      }
      return fs.createReadStream(__dirname + '/serverMockup/' + command + '.xml').pipe(res);
    });
  };

  discover = dgram.createSocket('udp4');

  discover.msg = new Buffer(fs.readFileSync(__dirname + '/serverMockup/Probe.xml').toString().replace('SERVICE_URI', 'http://localhost:' + (process.env.PORT || 10101) + '/onvif/device_service'));

  discover.on('error', function(err) {
    throw err;
  });

  discover.on('message', function(msg, rinfo) {
    var msgId;
    msgId = /urn:uuid:([0-9a-f\-]+)</.exec(msg.toString())[1];
    if (msgId) {
      switch (msgId) {
        case 'e7707':
          return discover.send(new Buffer('lollipop'), 0, 8, rinfo.port, rinfo.address);
        case 'd0-61e':
          discover.send(discover.msg, 0, discover.msg.length, rinfo.port, rinfo.address);
          return discover.send(discover.msg, 0, discover.msg.length, rinfo.port, rinfo.address);
        default:
          return discover.send(discover.msg, 0, discover.msg.length, rinfo.port, rinfo.address);
      }
    }
  });

  discover.bind(3702, function() {
    return discover.addMembership('239.255.255.250');
  });

  module.exports = http.createServer(listener).listen(process.env.PORT || 10101);

}).call(this);

//# sourceMappingURL=serverMockup.js.map
