// Generated by CoffeeScript 1.7.1
(function() {
  var Cam, assert, serverMockup;

  assert = require('assert');

  Cam = require('../lib/onvif').Cam;

  serverMockup = require('./serverMockup');

  describe('Simple and common get functions', function() {
    var cam;
    cam = null;
    before(function(done) {
      return cam = new Cam({
        hostname: 'localhost',
        username: 'admin',
        password: '9999',
        port: 10101
      }, done);
    });
    return describe('getSystemDateAndTime', function() {
      return it('should return valid date', function(done) {
        return cam.getSystemDateAndTime(function(err, data) {
          assert.equal(err, null);
          assert.deepEqual(Object.keys(data), ['time', 'date']);
          assert.deepEqual(Object.keys(data.time), ['hour', 'minute', 'second']);
          assert.deepEqual(Object.keys(data.date), ['year', 'month', 'day']);
          assert.ok(Object.keys(data.time).every(function(key) {
            return typeof data.time[key] === 'number';
          }));
          assert.ok(Object.keys(data.date).every(function(key) {
            return typeof data.date[key] === 'number';
          }));
          return done();
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=simple.map
