// Generated by CoffeeScript 1.7.1
(function() {
  var Cam, assert, serverMockup;

  assert = require('assert');

  Cam = require('../lib/onvif').Cam;

  serverMockup = require('./serverMockup');

  describe('Simple and common get functions', function() {
    var cam;
    cam = null;
    before(function(done) {
      return cam = new Cam({
        hostname: 'localhost',
        username: 'admin',
        password: '9999',
        port: 10101
      }, done);
    });
    return describe('getSystemDateAndTime', function() {
      return it('should return valid date', function(done) {
        return cam.getSystemDateAndTime(function(err, data) {
          assert.ok(data instanceof Date);
          return done();
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=simple.map
