// Generated by CoffeeScript 1.7.1
(function() {
  var Cam;

  Cam = require('../lib/onvif').Cam;

  exports.cam = new Cam({
    hostname: '192.168.68.111',
    username: 'admin',
    password: '9999'
  });

}).call(this);

//# sourceMappingURL=cam.map
