// Generated by CoffeeScript 1.7.1
(function() {
  var Cam, assert;

  assert = require('assert');

  Cam = require('../lib/onvif').Cam;

  describe('getCapabilities', function() {
    var cam;
    cam = new Cam({
      hostname: '192.168.68.111',
      username: 'admin',
      password: '9999'
    });
    return it('should get capabilities', function(done) {
      return cam.getCapabilities(function(err, data) {
        assert.equal(err, null);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=getCapabilites.map
