// Generated by CoffeeScript 1.7.1
(function() {
  var assert, cam;

  assert = require('assert');

  cam = require('./cam').cam;

  describe('getProfiles', function() {
    return it('should get profiles', function(done) {
      return cam.getProfiles(function(err, data) {
        assert.equal(err, null);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=getProfiles.map
