// Generated by CoffeeScript 1.7.1
(function() {
  var Cam, assert;

  assert = require('assert');

  Cam = require('../lib/onvif').Cam;

  describe('getSystemDateAndTime', function() {
    var cam;
    cam = new Cam({
      hostname: '192.168.68.111'
    });
    return it('sould return current date', function(done) {
      return cam.getSystemDateAndTime(function(err, data) {
        console.log(err, data);
        assert.equal(err, null);
        assert.deepEqual(Object.keys(data), ['year', 'month', 'day', 'hour', 'minute', 'second']);
        assert.ok(Object.keys(data).every(function(key) {
          return typeof data[key] === 'number';
        }));
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=getSystemDateAndTime.map
