// Generated by CoffeeScript 1.7.1
(function() {
  var Cam, assert;

  assert = require('assert');

  Cam = require('../lib/onvif').Cam;

  describe('getCapabilities', function() {
    var cam;
    cam = new Cam({
      hostname: '192.168.68.111',
      username: 'admin',
      password: '9999'
    });
    return it('should get video sources', function(done) {
      return cam.getVideoSources(function(err, data) {
        console.log(JSON.stringify(data));
        assert.equal(err, null);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=getVideoSources.map
