name: Test
on:
  pull_request:
    branches: [ "master", "v1" ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x,20.x,22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      # can be used to compile TS -> JS prior to testing if needed
      - run: npm run build --if-present
      - run: npm test
      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
        if: matrix.node-version == '16.x'
